spring:
  application:
    name: pokupka24
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:pokupka24&serverTimezone=UTC;
    username: sa
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql

server:
  port: 13000
#  servlet:
#    context-path: /pokupka24

management:
  endpoints:
    web:
      exposure:
        include: health,info,beans,mappings
  info:
    env:
      enabled: true

info:
  app:
    name: Pokupka24
    info: Shop. Smile. Repeat.
    author: Dima
  notApp: something
