spring:
  application:
    name: pokupka24
  datasource:
    driverClassName: org.h2.Driver
    password: ''
#    url: jdbc:h2:mem:pokupka24
    url: jdbc:h2:./h2/pokupka24;AUTO_SERVER=TRUE
    username: sa
  h2:
    console:
      enabled: true
      path: /console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:db/schema.sql
#      data-locations: classpath:db/data.sql
  liquibase:
#    change-log: classpath:db/liquibase/liquibase-outputChangeLog.xml
    changeLog: classpath:db/liquibase/changelog-root.xml
    url: jdbc:h2:./h2/pokupka24;IFEXISTS=TRUE
    user: sa
    password: ''
#    contexts: dev
#    enabled: false

server:
  port: 13000
#  servlet:
#    context-path: /pokupka24

management:
  endpoints:
    web:
      exposure:
        include: "*"
#        include: health,info,beans,mappings,loggers,prometheus,metrics
  info:
    env:
      enabled: true

springdoc:
  swagger-ui:
    operations-sorter: method

info:
  app:
    name: Pokupka24
    info: Shop. Smile. Repeat.
    author: Dima
  notApp: something

task:
  cron:
#    birthday-present: 0 10 0 * * ?
    birthday-present: 30 * * * * ?
#    birthday-present: @midnight

timezone: Europe/Moscow
