spring:
  application:
    name: pokupka24
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:pokupka24&serverTimezone=UTC;
    username: sa
#  h2:
#    console:
#      enabled: true
#      path: /console
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql

server:
  port: 13000
#  servlet:
#    context-path: /pokupka24

management:
  endpoints:
    web:
      exposure:
        include: "*"
#        include: health,info,beans,mappings,loggers,prometheus,metrics
  info:
    env:
      enabled: true

springdoc:
  swagger-ui:
    operations-sorter: method

info:
  app:
    name: Pokupka24
    info: Shop. Smile. Repeat.
    author: Dima
  notApp: something
